config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :transportes

  resources :centros

  resources :personals

  root 'personals#index'

end

app/models/personal.rb
class Personal < ActiveRecord::Base
    
    
    #generador de archivo excel
    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |personal|
          csv << personal.attributes.values_at(*column_names)
        end
      end
    end 
    
  
    belongs_to :usuario
    belongs_to :transporte
    belongs_to :centro
    
    

    #validaciones para los campos a llenar
    validates :nombres, :presence => true
    validates :apellidos, :presence => true
    
    #validacion de atributos unicos
    validates :cedula, :presence => true, uniqueness: { message: "No se puede Repetir" }
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
   message: 'Formato no valido' }
   
   validates :ficha, :presence => true

    validates :transporte_id, :presence => true
     validates :usuario_id, :presence => true
    
    validates :placa, :presence => true, uniqueness: { message: "no se puede Repetir" }
    
    validates :centro_id, :presence => true
    validates :celular, :presence => true
    
    def self.search(search, page)
        where(['upper(placa) like ?',
        "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("placa")
    end
	
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_personal, only: [:show, :edit, :update, :destroy]

  # GET /personals
  # GET /personals.json
  def index
    @personals = Personal.search(params[:search], params[:page]) 
    @fondo = true
    
    
    respond_to do |format|
      format.html
      format.csv { send_data @personals.to_csv }
      
    end
    
  end

  # GET /personals/1
  # GET /personals/1.json
  def show
    @fondo2 = true
  end

  # GET /personals/new
  def new
    @personal = Personal.new
  end

  # GET /personals/1/edit
  def edit
  end

  # POST /personals
  # POST /personals.json
  def create
    @personal = Personal.new(personal_params)

    respond_to do |format|
      if @personal.save
        format.html { redirect_to @personal, notice: 'Personal was successfully created.' }
        format.json { render :show, status: :created, location: @personal }
      else
        format.html { render :new }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personals/1
  # PATCH/PUT /personals/1.json
  def update
    respond_to do |format|
      if @personal.update(personal_params)
        format.html { redirect_to @personal, notice: 'Personal was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal }
      else
        format.html { render :edit }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personals/1
  # DELETE /personals/1.json
  def destroy
    @personal.destroy
    respond_to do |format|
      format.html { redirect_to personals_url, notice: 'Personal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal
      @personal = Personal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_params
      params.require(:personal).permit(:usuario_id, :nombres, :apellidos, :cedula, :ficha, :centro_id, :email, :placa, :color_vehiculo, :telefono_ip, :celular, :transporte_id)
    end
end

app/helpers/personals_helper.rb
module PersonalsHelper

end

app/views/personals/_form.html.erb
<body class="fondo3">
  
  
<%= form_for(@personal) do |f| %>
  <% if @personal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal.errors.count, "error") %> prohibited this personal from being saved:</h2>

      <ul>
      <% @personal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="col-md-12">
    <div class="col-md-6">
    <div class="field">
     <h4 class="letra2">Usuario</h4>
    <%= f.collection_select :usuario_id, Usuario.all, :id, :nombre,{prompt: "seleccione usuario"}, {class:'form-control'} %>
</div>
  
  </div>


  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Nombres</h4>
    <%= f.text_field :nombres, class: "form-control" %>
  </div>
    
  </div>
  </div>
  
  <div class="col-md-12">
  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Apellidos</h4>
    <%= f.text_field :apellidos, class: "form-control" %>
   </div>
  </div>



  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Cedula</h4>
    <%= f.text_field :cedula, class: "form-control" %>
  </div>
    
  </div>
  </div>
  
  
  <div class="col-md-12">
    <div class="col-md-6">
      <div class="field">
        <h4 class="letra2">Ficha</h4>
        <%= f.text_field :ficha, class: "form-control" %>
      </div>
    </div>
  
  
    <div class="col-md-6">
      <div class="field">
        <h4 class="letra2">Centro</h4>
        <%= f.collection_select :centro_id, Centro.all, :id, :nombre, {prompt: "seleccione centro"}, {class:'form-control'} %>
      </div>
    
    </div>
  
</div>

  <div class="col-md-12">
  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Email</h4>
    <%= f.text_field :email, class: "form-control" %>
  </div>
    
  </div>
  
    
    
<div class="col-md-6">
    <div class="field">
     <h4 class="letra2">Transporte</h4>
    <%= f.collection_select :transporte_id, Transporte.all, :id, :vehiculo,{prompt: "seleccione Vehiculo"}, {class:'form-control'} %>
</div>
  </div>
  
  </div>

 <div class="col-md-12">
  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Placa</h4>
    <%= f.text_field :placa, class: "form-control" %>
  </div>
    
  </div>
  
  

  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Color del Vehiculo</h4>
    <%= f.text_field :color_vehiculo, class: "form-control" %>
   </div>
    
  </div>
  </div>

  <div class="col-md-12">
  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Telefono IP/Otro</h4>
    <%= f.text_field :telefono_ip, class: "form-control" %>
  </div>
    
  
  </div>

  <div class="col-md-6">
    <div class="field">
    <h4 class="letra2">Celular</h4>
    <%= f.text_field :celular, class: "form-control" %>
  </div>
    
  </div>
  
  </div>
  
  
  

  
  
  <div class="actions">
    <%= f.submit "Guardar", class: 'btn btn-info' %></div>
    <div class="btn btn-info">

<%= link_to 'ATRAS', personals_path %></div>
  
 
<% end %>

</body>

app/views/personals/edit.html.erb
<h1 class="texto3d">Editar Usuario</h1>

<div class="relleno2">

<%= render 'form' %></div>
<div class="btn btn-info">
<%= link_to 'Mostrar', @personal %>
</div>

app/views/personals/index.html.erb
<body class="fondo">
  <br>
  <div class="relleno">
    <h1 class="texto3d">Lista de Usuarios</h1>  


    <%= form_tag personals_path, :method => 'get' do %>
    <% content_tag :label do %>
    Buscar Placa vehiculo:
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Buscar",  :name => nil %>
   
    <% end %>
    <% end %>

<div class="scroll col-xs-12"><br>
  <table class="table table-hover margin" >
  <thead>
    <tr class="text">
      <th>usuario</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Transporte</th>
      <th>Placa</th>
      <th>Celular</th>
      <th>Ficha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="letra">
  
    <% @personals.each do |personal| %>
      <tr>
        <td><%= personal.usuario.nombre%></td>
        <td><%= personal.nombres %></td>
        <td><%= personal.apellidos %></td>
        <td><%= personal.transporte.vehiculo %></td>
        <td><%= personal.placa %></td>
        <td><%= personal.celular %></td>
        <td><%= personal.ficha %></td>
        <td><%= link_to "<i class='fa fa-neuter fa-2x encima'>".html_safe, personal %></td>
        <td><%= link_to "<i class='fa fa-edit fa-2x encima '></i>".html_safe, edit_personal_path(personal) %></td>
        <td><%= link_to "<i class='fa fa-trash-o fa-2x encima'>".html_safe, personal, method: :delete, data: { confirm: 'ESTAS SEGURO?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <br>
  
</div>


<br>
<div class="btn btn-info">

<%= link_to 'Nuevo Personal', new_personal_path %><br></div>

<div class="btn btn-info">
<%= link_to 'Atras', personals_path %></div>

<div class="btn btn-info">
        
        <%= link_to "Excel", personals_path(format: "csv") %> 
    </div>





 

<%= will_paginate @personals, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' %>
<br>
Personals: <%= @personals.count %>

  </div>
  
  
   
</body>

app/views/personals/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="personals">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Usuario</Data></Cell>
        <Cell><Data ss:Type="String">Nombres</Data></Cell>
        <Cell><Data ss:Type="String">Apellidos</Data></Cell>
        <Cell><Data ss:Type="String">Cedula</Data></Cell>
         <Cell><Data ss:Type="String">ficha</Data></Cell>
        <Cell><Data ss:Type="String">Centro</Data></Cell>
        <Cell><Data ss:Type="String">Transporte</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Placa</Data></Cell>
        <Cell><Data ss:Type="String">Color del Vehiculo</Data></Cell>
        <Cell><Data ss:Type="String">Telefono_ip</Data></Cell>
        <Cell><Data ss:Type="String">Celular</Data></Cell>
        
        
      </Row>
    <% @personals.each do |personal| %>
      <Row>
        <Cell><Data ss:Type="String"><%= personal.usuario.nombre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= personal.nombres %></Data></Cell>
        <Cell><Data ss:Type="String"><%= personal.apellidos %></Data></Cell>
        <Cell><Data ss:Type="string"><%= personal.cedula %></Data></Cell>
        <Cell><Data ss:Type="string"><%= personal.ficha %></Data></Cell>
        <Cell><Data ss:Type="String"><%= personal.centro.nombre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= personal.transporte.vehiculo %></Data></Cell>
        <Cell><Data ss:Type="string"><%= personal.email %></Data></Cell>
        <Cell><Data ss:Type="string"><%= personal.placa %></Data></Cell>
        <Cell><Data ss:Type="String"><%= personal.color_vehiculo %></Data></Cell>
        <Cell><Data ss:Type="String"><%= personal.telefono_ip %></Data></Cell>
        <Cell><Data ss:Type="String"><%= personal.cedula %></Data></Cell>
        
      </Row>
    <% end %>
    
    
    </Table>
  </Worksheet>
</Workbook>

app/views/personals/new.html.erb
<h1 class="texto3d">Nuevo Usuario</h1>

<div class="relleno2">

<%= render 'form' %>
</div>

app/views/personals/show.html.erb
  <body class="fondo2">
      
      <p id="notice"><%= notice %></p>
<div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h2 class="texto3d">Datos Del Usuario</h2>
            </div>
            
            
            <div class="col-md-12" style="margin-top: 20px;">
                <div class="pricing-table">
                    <div class="panel panel-primary" style="border: none;">
                        
                        
                        <div class="panel-body panel-body-landing">
                            <table class="table">
                                 
                                 <tr>
                                    <td><strong>Usuario</strong></td>
                                    <td><%= @personal.usuario.nombre rescue nil  %></td>
                                </tr>
                                
                                <tr>
                                    <td><strong>Nombres</strong></td>
                                    <td><%= @personal.nombres%></td>
                                </tr>
                                
                                <tr>
                                    <td><strong>Apellidos</strong></td>
                                    <td><%= @personal.apellidos %></td>
                                </tr>
                                
                                <tr>
                                    <td><strong>Cedula</strong></td>
                                    <td><%= @personal.cedula %></td>
                                </tr>
                                
                                 <tr>
                                    <td><strong>Ficha</strong></td>
                                    <td><%= @personal.ficha %></td>
                                </tr>
                                
                                <tr>
                                    <td><strong>Centro</strong></td>
                                    <td><%= @personal.centro.nombre rescue nil  %></td>
                                </tr>
                                
                                <tr>
                                    <td width="50px"><strong>Email</strong></td>
                                    <td><%= @personal.email %></td>
                                </tr>
                                
                                <tr>
                                    <td><strong>Vehiculo</strong></td>
                                    <td><%= @personal.transporte.vehiculo rescue nil%></td>
                                </tr>
                                
                                 <tr>
                                    <td width="50px"><strong>Placa</strong></td>
                                    <td><%= @personal.placa %></td>
                                 </tr>
                                 
                                 <tr>
                                    <td width="50px"><strong>Color</strong></i></td>
                                    <td><%= @personal.color_vehiculo %></td>
                                 </tr>
                                
                                 <tr>
                                    <td width="50px"><strong>Telefono IP/Otro</strong></i></td>
                                    <td><%= @personal.telefono_ip %></td>
                                 </tr>
                                 
                                 <tr>
                                    <td width="50px"><strong>Celular</strong></i></td>
                                    <td><%= @personal.celular %></td>
                                 </tr>
                                 
                            </table>
                        </div>
                        <div  class="btn btn-info">
                             <%= link_to 'Editar', edit_personal_path(@personal) %> |
                             <%= link_to 'Atras', personals_path %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
      
  </body>
                          
                          
        
  