config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :transportes

  resources :centros

  resources :personals

  root 'personals#index'

end

app/models/transporte.rb
class Transporte < ActiveRecord::Base
    has_many :transportes
end

app/controllers/transportes_controller.rb
class TransportesController < ApplicationController
  before_action :set_transporte, only: [:show, :edit, :update, :destroy]

  # GET /transportes
  # GET /transportes.json
  def index
    @transportes = Transporte.all
  end

  # GET /transportes/1
  # GET /transportes/1.json
  def show
  end

  # GET /transportes/new
  def new
    @transporte = Transporte.new
  end

  # GET /transportes/1/edit
  def edit
  end

  # POST /transportes
  # POST /transportes.json
  def create
    @transporte = Transporte.new(transporte_params)

    respond_to do |format|
      if @transporte.save
        format.html { redirect_to @transporte, notice: 'Transporte was successfully created.' }
        format.json { render :show, status: :created, location: @transporte }
      else
        format.html { render :new }
        format.json { render json: @transporte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transportes/1
  # PATCH/PUT /transportes/1.json
  def update
    respond_to do |format|
      if @transporte.update(transporte_params)
        format.html { redirect_to @transporte, notice: 'Transporte was successfully updated.' }
        format.json { render :show, status: :ok, location: @transporte }
      else
        format.html { render :edit }
        format.json { render json: @transporte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transportes/1
  # DELETE /transportes/1.json
  def destroy
    @transporte.destroy
    respond_to do |format|
      format.html { redirect_to transportes_url, notice: 'Transporte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transporte
      @transporte = Transporte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transporte_params
      params.require(:transporte).permit(:vehiculo)
    end
end

app/helpers/transportes_helper.rb
module TransportesHelper
end

app/views/transportes/_form.html.erb
<%= form_for(@transporte) do |f| %>
  <% if @transporte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transporte.errors.count, "error") %> prohibited this transporte from being saved:</h2>

      <ul>
      <% @transporte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehiculo %><br>
    <%= f.text_field :vehiculo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transportes/edit.html.erb
<h1>Editing transporte</h1>

<%= render 'form' %>

<%= link_to 'Show', @transporte %> |
<%= link_to 'Back', transportes_path %>

app/views/transportes/index.html.erb
<h1>Listing transportes</h1>

<table>
  <thead>
    <tr>
      <th>Vehiculo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transportes.each do |transporte| %>
      <tr>
        <td><%= transporte.vehiculo %></td>
        <td><%= link_to 'Show', transporte %></td>
        <td><%= link_to 'Edit', edit_transporte_path(transporte) %></td>
        <td><%= link_to 'Destroy', transporte, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transporte', new_transporte_path %>

app/views/transportes/new.html.erb
<h1>New transporte</h1>

<%= render 'form' %>

<%= link_to 'Back', transportes_path %>

app/views/transportes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehiculo:</strong>
  <%= @transporte.vehiculo %>
</p>

<%= link_to 'Edit', edit_transporte_path(@transporte) %> |
<%= link_to 'Back', transportes_path %>