config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :transportes

  resources :centros

  resources :personals

  root 'personals#index'

end

app/models/centro.rb
class Centro < ActiveRecord::Base
    has_many :personals
end

app/controllers/centros_controller.rb
class CentrosController < ApplicationController
  before_action :set_centro, only: [:show, :edit, :update, :destroy]

  # GET /centros
  # GET /centros.json
  def index
    @centros = Centro.all
  end

  # GET /centros/1
  # GET /centros/1.json
  def show
  end

  # GET /centros/new
  def new
    @centro = Centro.new
  end

  # GET /centros/1/edit
  def edit
  end

  # POST /centros
  # POST /centros.json
  def create
    @centro = Centro.new(centro_params)

    respond_to do |format|
      if @centro.save
        format.html { redirect_to @centro, notice: 'Centro was successfully created.' }
        format.json { render :show, status: :created, location: @centro }
      else
        format.html { render :new }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centros/1
  # PATCH/PUT /centros/1.json
  def update
    respond_to do |format|
      if @centro.update(centro_params)
        format.html { redirect_to @centro, notice: 'Centro was successfully updated.' }
        format.json { render :show, status: :ok, location: @centro }
      else
        format.html { render :edit }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centros/1
  # DELETE /centros/1.json
  def destroy
    @centro.destroy
    respond_to do |format|
      format.html { redirect_to centros_url, notice: 'Centro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centro
      @centro = Centro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centro_params
      params.require(:centro).permit(:nombre)
    end
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/views/centros/_form.html.erb
<%= form_for(@centro) do |f| %>
  <% if @centro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@centro.errors.count, "error") %> prohibited this centro from being saved:</h2>

      <ul>
      <% @centro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre%><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/centros/edit.html.erb
<h1>Editing centro</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @centro %> |
<%= link_to 'Atras', centros_path %>

app/views/centros/index.html.erb
<h1>Listing centros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centros.each do |centro| %>
      <tr>
        <td><%= centro.nombre %></td>
        <td><%= link_to 'Show', centro %></td>
        <td><%= link_to 'Edit', edit_centro_path(centro) %></td>
        <td><%= link_to 'Destroy', centro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Centro', new_centro_path %>

app/views/centros/new.html.erb
<h1>New centro</h1>

<%= render 'form' %>

<%= link_to 'Back', centros_path %>

app/views/centros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @centro.nombre %>
</p>

<%= link_to 'Edit', edit_centro_path(@centro) %> |
<%= link_to 'Back', centros_path %>